### ISSUE TITLE
Why apex instead of mmdet's fp16?

### ISSUE THREAD

**Issue by shinya7y** [SwinTransformer/Swin-Transformer-Object-Detection#1]
Thank you for publishing the great work!

> We use apex for mixed precision training by default.
> \# do not use mmdet version fp16

Why does the code use apex instead of mmdet's fp16?
Are there any difference in AP, training speed, and inference speed?

**Comment by impiga** [comment]
Thanks for your interest! 
In our experiments, apex was more stable than mmdet's fp16. So we adopt apex.

**Comment by shinya7y** [comment]
Thank you for your answer.

In my environment, PyTorch 1.7.1 works, but PyTorch 1.8.1 doesn't work.
To start training with mmdet's fp16, I needed to replace this line
https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/02baa301774b455fe8e57ef9dc0fc32ef2ba2bb6/mmdet/models/backbones/swin_transformer.py#L150
with `x = (attn.type_as(v) @ v).transpose(1, 2).reshape(B_, N, C)`.
