### ISSUE TITLE
cv2.error

### ISSUE THREAD

**Issue by xuhao-anhe** [SwinTransformer/Swin-Transformer-Object-Detection#106]
Thank the author for his contribution，when I use 
mask_ rcnn_ swin_ tiny_ patch4_ window7_ mstrain_ 400-800_ adamw_ 1x_ Coco.py 
to perform strength segmentation training on my own data set。
Program appears OpenCV(3.4.4) /io/opencv/modules/core/src/copy.cpp:1186: error :(-215:Assertion failed) top >=0 && bottom >= 0 && left >=0 && right >=0 && _src.dims() <=2 in function 'copyMakeBorder'。
I tried to change the file paths to absolute paths, but in the end, an error was reported。I hope the author can answer。

**Comment by BakingBrains** [comment]
@xuhao-anhe Did you solved this error?

Thanks

**Comment by tintranrynan** [comment]
Did you solve this problem?
Please help me
