### ISSUE TITLE
name "apex" is not defined 

### ISSUE THREAD

**Issue by Beyond-AA** [SwinTransformer/Swin-Transformer-Object-Detection#107]
Error under Windows system:
      name "apex" is not defined

**Comment by cccyyy24** [comment]
好像是不要安装最新版本

**Comment by cccyyy24** [comment]
> Error under Windows system: name "apex" is not defined

n你好 你解决了吗

**Comment by Beyond-AA** [comment]
在你虚拟环境下的site-packages\apex-0.1-py3.7.egg\apex\transformer\pipeline_parallel文件夹，找到utils.py并打开并将import amp_C改为#import amp_C，屏蔽之后就可以了

**Comment by cccyyy24** [comment]
> 在你虚拟环境下的site-packages\apex-0.1-py3.7.egg\apex\transformer\pipeline_parallel文件夹，找到utils.py并打开并将import amp_C改为#import amp_C，屏蔽之后就可以了
你好，你跑通了吗？我们可以加微信交流一下吗（微信 cy1203hg_）

**Comment by impiga** [comment]
Close this issue as it has been resolved in this comment.

> 在你虚拟环境下的site-packages\apex-0.1-py3.7.egg\apex\transformer\pipeline_parallel文件夹，找到utils.py并打开并将import amp_C改为#import amp_C，屏蔽之后就可以了

**Comment by ibtehajali67** [comment]
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

I resolved using these commands
