### ISSUE TITLE
Typeerror："NoneType" object is not iterable

### ISSUE THREAD

**Issue by eduo97** [SwinTransformer/Swin-Transformer-Object-Detection#121]
Typeerror："NoneType" object is not iterable

**Comment by impiga** [comment]
Hi, @eduo97 . Could you provide more details, like your config and all the error messages?

**Comment by eduo97** [comment]
> Hi, @eduo97 . Could you provide more details, like your config and all the error messages?

This is related to the data I use and I have solved it

**Comment by Piggytuotuo** [comment]
the same issue, how did you solve it?

**Comment by THEBEST-cloud** [comment]
I also encountered this problem, can you tell me how to solve this problem?

**Comment by slowlypasser** [comment]
> 
Cloud you share how to solve this？thanks a lot！
