### ISSUE TITLE
Attempt for SwinTransformer + Faster RCNN

### ISSUE THREAD

**Issue by wliebtzy** [SwinTransformer/Swin-Transformer-Object-Detection#124]
Hello,
I tried to perform Swin Transformer as a backbone to feed the feature map into Faster RCNN. I used the config of Swin Transformer and FPN from the file "configs/base/models/mask_rcnn_swin_fpn.py" and the rpn_head and roi_head from "configs/base/models/faster_rcnn_r50_fpn.py", in order to construct a new architecture for object detection. Then the pretrained file "swin_tiny_patch4_window7_224.pth" has been imported. But as shown in the console, "The model and loaded state dict do not match exactly".
I wonder whether I make some mistakes across the construction of the architecture or the utilization of the pretrained model?

**Comment by wliebtzy** [comment]
Hello,
I tried to perform Swin Transformer as a backbone to feed the feature map into Faster RCNN. I used the config of Swin Transformer and FPN from the file "configs/_base_/models/mask_rcnn_swin_fpn.py" and the rpn_head and roi_head from  "configs/_base_/models/faster_rcnn_r50_fpn.py", in order to construct a new architecture for object detection. Then the pretrained file "swin_tiny_patch4_window7_224.pth" has been imported. But as shown in the console, "The model and loaded state dict do not match exactly".
I wonder whether I make some mistakes across the construction of the architecture or the utilization of the pretrained model?

**Comment by impiga** [comment]
Hi, does the information look like this:
```
unexpected key in source state_dict: norm.weight, norm.bias, head.weight, head.bias, layers.0.blocks.1.attn_mask, layers.1.blocks.1.attn_mask, layers.2.blocks.1.attn_mask, layers.2.blocks.3.attn_mask, layers.2.blocks.5.attn_mask, layers.2.blocks.7.attn_mask, layers.2.blocks.9.attn_mask, layers.2.blocks.11.attn_mask, layers.2.blocks.13.attn_mask, layers.2.blocks.15.attn_mask, layers.2.blocks.17.attn_mask

missing keys in source state_dict: norm0.weight, norm0.bias, norm1.weight, norm1.bias, norm2.weight, norm2.bias, norm3.weight, norm3.bias
```

If this is the warning message, it is OK to ignore them. Reasons are described below.

For the unexpected keys of 'norm.xxx' and missing keys of 'normx.xxx': The pre-training classification network only uses the output of the last layer and appends a norm layer after this output. So it has parameters with names of `norm.weight` and `norm.bias`. However, in the detection network, multi-scale outputs from different layers are utilized. Multiple norm layers are added after these outputs. So the detection network has parameters from `norm0` to `norm3`.

For the unexpected keys of `head.xxx`:  This is the 1000-category linear classifier. It is not used in detection network.

For the unexpected keys of `attn_mask`: They are used for `cyclic window` and are NOT learnable parameters. In detection, `attn_mask` would be re-computed for each image as input images may have different resolutions.

**Comment by wliebtzy** [comment]
>Got it. Thanks very much!

**Comment by tdougherty84** [comment]
@wliebtzy were you able to get SWIN+Faster RCNN working with the pretrained weights? Happen to share code or steps on getting it working? Thanks!

**Comment by GingerCohle** [comment]
> Hi, does the information look like this:
> 
> ```
> unexpected key in source state_dict: norm.weight, norm.bias, head.weight, head.bias, layers.0.blocks.1.attn_mask, layers.1.blocks.1.attn_mask, layers.2.blocks.1.attn_mask, layers.2.blocks.3.attn_mask, layers.2.blocks.5.attn_mask, layers.2.blocks.7.attn_mask, layers.2.blocks.9.attn_mask, layers.2.blocks.11.attn_mask, layers.2.blocks.13.attn_mask, layers.2.blocks.15.attn_mask, layers.2.blocks.17.attn_mask
> 
> missing keys in source state_dict: norm0.weight, norm0.bias, norm1.weight, norm1.bias, norm2.weight, norm2.bias, norm3.weight, norm3.bias
> ```
> 
> If this is the warning message, it is OK to ignore them. Reasons are described below.
> 
> For the unexpected keys of 'norm.xxx' and missing keys of 'normx.xxx': The pre-training classification network only uses the output of the last layer and appends a norm layer after this output. So it has parameters with names of `norm.weight` and `norm.bias`. However, in the detection network, multi-scale outputs from different layers are utilized. Multiple norm layers are added after these outputs. So the detection network has parameters from `norm0` to `norm3`.
> 
> For the unexpected keys of `head.xxx`: This is the 1000-category linear classifier. It is not used in detection network.
> 
> For the unexpected keys of `attn_mask`: They are used for `cyclic window` and are NOT learnable parameters. In detection, `attn_mask` would be re-computed for each image as input images may have different resolutions.

Ty for the explanation!!!!!
