### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'embed_dim'

### ISSUE THREAD

**Issue by LUO77123** [SwinTransformer/Swin-Transformer-Object-Detection#131]
**Notice**

Traceback (most recent call last):
  File "f:\peizhiwenjian\mmcv-1.4.0\mmcv\utils\registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\peizhiwenjian\mmcv-1.4.0\mmcv\utils\registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "f:\peizhiwenjian\mmdetection-master2.19.1\mmdet\models\detectors\mask_rcnn.py", line 19, in __init__
    super(MaskRCNN, self).__init__(
  File "f:\peizhiwenjian\mmdetection-master2.19.1\mmdet\models\detectors\two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "f:\peizhiwenjian\mmdetection-master2.19.1\mmdet\models\builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "f:\peizhiwenjian\mmcv-1.4.0\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "f:\peizhiwenjian\mmcv-1.4.0\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "f:\peizhiwenjian\mmcv-1.4.0\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\PYcharm-project\deep-learning-for-image-processing\pytorch_object_detection\Swin-Transformer-Object-Detection-master\demo\image_demo.py", line 26, in <module>
    main()
  File "F:\PYcharm-project\deep-learning-for-image-processing\pytorch_object_detection\Swin-Transformer-Object-Detection-master\demo\image_demo.py", line 18, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "f:\peizhiwenjian\mmdetection-master2.19.1\mmdet\apis\inference.py", line 40, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "f:\peizhiwenjian\mmdetection-master2.19.1\mmdet\models\builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "f:\peizhiwenjian\mmcv-1.4.0\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "f:\peizhiwenjian\mmcv-1.4.0\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "f:\peizhiwenjian\mmcv-1.4.0\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MaskRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

**Comment by LUO77123** [comment]
TorchVision: 0.11.1
OpenCV: 4.5.4-dev
MMCV: 1.4.0
MMCV Compiler: MSVC 192930040
MMCV CUDA Compiler: 11.5
MMDetection: 2.19.1+

**Comment by LUO77123** [comment]
i solved it by run python setup.py develop in Swin-Transformer-Object-Detection folder

**Comment by jimmy-xiaoke-shen** [comment]
For the config file, update "embed_dim" to "embed_dims"

**Comment by twwinniejiang** [comment]
I have the same problem, how to solve it?

**Comment by sfarkya04** [comment]
I was facing the same issue with the versions and tried couple of combinations of **mmcv-full** and **mmdet** and this works for me. Not sure if it will work for all. 

```
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

pip install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
python setup.py develop # run this in the Swin-Transformer-Object-Detection main directory
pip install mmpycocotools
pip install mmdet

```

**Comment by twwinniejiang** [comment]
> I was facing the same issue with the versions and tried couple of combinations of **mmcv-full** and **mmdet** and this works for me. Not sure if it will work for all.
> 
> ```
> pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
> 
> pip install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
> python setup.py develop # run this in the Swin-Transformer-Object-Detection main directory
> pip install mmpycocotools
> pip install mmdet
> ```

Hi , Thank you very reply my issue.

i will try suggest.

**Comment by twwinniejiang** [comment]
> I was facing the same issue with the versions and tried couple of combinations of **mmcv-full** and **mmdet** and this works for me. Not sure if it will work for all.
> 
> ```
> pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
> 
> pip install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
> python setup.py develop # run this in the Swin-Transformer-Object-Detection main directory
> pip install mmpycocotools
> pip install mmdet
> ```

please ask , you use system is ubuntu ?

**Comment by sfarkya04** [comment]
@twwinniejiang 
Yes, I am using Ubuntu 18.04 and I am installing the above packages inside a docker container. 
I have CUDA 11.0 installed on my system.

**Comment by sfarkya04** [comment]
You can run the above commands without docker as well. 
Better to create a virtual env and then do it. 
Just copy paste on terminal or create a bash file

**Comment by HMPgit** [comment]
I have to run it on HPC and when I tried to "python setup.py develop". I got a permission Error! It seems the only way for me is to create a docker image and run it on HPC.

**Comment by sfarkya04** [comment]
FYI, You should run that command in Swin-Transformer-Object-Detection directory. 

If you are still getting a permission error then you have to create a virtual env. That doesn't require root permissions usually. 
And if you still need a docker env here's mine: https://github.com/sfarkya/nvim-python
This is a vim complete development setup. 

You can copy-paste above commands in the Dockerfile in the git above.

**Comment by HMPgit** [comment]
Yes, I got the permission error in Swin-Transformer-Object-Detection directory. I will go forward with the other two options. Thank you so much.

**Comment by HMPgit** [comment]
@sfarkya04: I got the following error when trying to build your docker.
![image](https://user-images.githubusercontent.com/50717775/154366952-91dd53e0-0511-4ad0-9ff0-e375e045eefe.png)

Also, I tried to create another docker, but I face the following error:
![Questionongithub1](https://user-images.githubusercontent.com/50717775/154367071-787605bd-cc67-449e-8cdc-90cdb6d0f653.PNG)

**Comment by sfarkya04** [comment]
Sorry, it's been a while I update the dockerfile. 
Anyways, you don't need all the vim stuff. 

In your new docker file, 
Seems like a python version error. Please check the python version, it should not be Python 2.x, update it to 3.7 or 3.x

**Comment by sfarkya04** [comment]
Do you mind sharing your dockerfile here?

**Comment by HMPgit** [comment]
@sfarkya04: I was able to build the docker and push it. 
But running "python demo/image_demo.py demo/demo.jpg" gave me the following error (I am inside the folder Swin-Transformer-Object-Detection): 
![image](https://user-images.githubusercontent.com/50717775/154754596-37f95b28-665e-4f5d-9c31-0c29939df388.png)

pip list shows the following:
![image](https://user-images.githubusercontent.com/50717775/154754761-3f4d5622-d001-49a7-8f18-7f996c80f1b2.png)

Running "python3 demo/image_demo.py demo/demo.jpg" gave me the following error:
![image](https://user-images.githubusercontent.com/50717775/154755058-0f4e2096-9ec5-42cc-b3ae-1e36c1f1a003.png)

and Running "python3.7 demo/image_demo.py demo/demo.jpg" gave me the following error:
![image](https://user-images.githubusercontent.com/50717775/154755169-d8041498-397d-4728-9339-bf566de907eb.png)

**Comment by sfarkya04** [comment]
This is the right command if you had built the docker based on the above commands. 
"python3.7 demo/image_demo.py demo/demo.jpg"  

It's an opencv version issue. You need to correctly install opencv with the right dependencies. It's a common issue that can be found on StackOverflow.

**Comment by HMPgit** [comment]
to address the error "libGL.so.1"
I added this line to the dockerfile
RUN apt-get install -y libglu1-mesa-dev

and to address the error "libgthread-2.0.so.0"
I added this line to the dockerfile
RUN apt-get install -y libglib2.0-0

Then I built and push the docker file. I got the exact same error as the original docker provided by the authors "embed_dim". 

I also tried to fix "embed_dim to embed_dims" in both files "mask_rcnn_swin_fpn.py" and "mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_1x_coco" and I got the error regarding 'ape' just like the official docker by authors. 
![image](https://user-images.githubusercontent.com/50717775/154773958-ff000f99-4e58-4877-bade-56666c612dc4.png)

**Comment by sfarkya04** [comment]
Try this, I tested this end to end: 

```
FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04

RUN apt-get update --fix-missing
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata locales
RUN ln -fs /usr/share/zoneinfo/US/Eastern /etc/localtime && dpkg-reconfigure -f noninteractive tzdata
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
RUN locale-gen

RUN apt-get install -y software-properties-common make autoconf automake \
    pkg-config gcc build-essential g++  git wget libperl-dev cmake \
    fonts-powerline exuberant-ctags inetutils-ping libclang1 tmux \
    xauth curl  latexmk gettext libtool libtool-bin autoconf \
    cmake pkg-config unzip make build-essential libssl-dev zlib1g-dev  \
    libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
    xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev curl neovim

RUN apt-get install -y python3.7 python3.7-dev
RUN apt-get install -y python3-setuptools
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.7 get-pip.py
RUN python3.7 -V && pip3 -V
RUN pip install opencv-python cython


RUN pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
RUN git clone https://github.com/SwinTransformer/Swin-Transformer-Object-Detection.git
WORKDIR /Swin-Transformer-Object-Detection
RUN python3.7 setup.py develop

RUN pip uninstall mmdet mmcv mmcv-full
RUN pip install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
RUN pip install mmpycocotools
RUN pip install mmdet
```
Build using this command: 
`docker build -t git/docker  .`

I ran it using this command inside the docker: 
```
DET_CHECKPOINT_FILE=./checkpoints/mask_rcnn_swin_tiny_patch4_window7.pth # put your model here download it from here : https://github.com/SwinTransformer/storage/releases/download/v1.0.3/mask_rcnn_swin_tiny_patch4_window7_1x.pth
CONFIG_FILE=./configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.py
python3.7 demo/image_demo.py demo/demo.jpg $CONFIG_FILE $DET_CHECKPOINT_FILE
```

**Comment by HMPgit** [comment]
Using the above docker image, and "bash run.sh", I get the following (I printed variable "result" in "image_demo.py"): 

![image](https://user-images.githubusercontent.com/50717775/155193517-3a2f4c5b-181f-4536-a388-35b717c37ead.png)

I tried to install apex in the docker file by adding the following two lines to the docker file:
![image](https://user-images.githubusercontent.com/50717775/155193675-0966ef3e-fd62-4bb6-a116-4e65bddf1ab1.png)

Using the new docker file, I still got the same missing apex:
![image](https://user-images.githubusercontent.com/50717775/155194740-c631b663-e295-40df-9269-02fa165a4c0f.png)

**Comment by jayes97** [comment]
> I was facing the same issue with the versions and tried couple of combinations of **mmcv-full** and **mmdet** and this works for me. Not sure if it will work for all. System Configs: OS: Ubuntu 18.04 CUDA: 11.0 VirtualEnv: Docker container
> 
> ```
> 
> git clone https://github.com/SwinTransformer/Swin-Transformer-Object-Detection.git swinTxs
> cd swinTxs
> python setup.py develop # run this in the Swin-Transformer-Object-Detection main directory
> 
> pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
> pip install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
> pip install mmpycocotools
> pip install mmdet
> ```


I don't know how this is working but yeah it will solve the error. you can try Latest also
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
pip install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
pip install mmpycocotools
pip install mmdet

and Done!!

**Comment by sfarkya04** [comment]
I was able to run with multiple such configurations; the hack to make some changes in code like removing "embed_dims", "apes" etc. There are multiple issues that solve that problem. 

The current version of the code worked only for the config I have above.

**Comment by k-arthik-raj** [comment]
Does anyone know how to make it work with cuda 11.3, as mmcv-full 1.3.17 is not compatible with cuda 11.3
