### ISSUE TITLE
where is Mask RepPoints V2  config?

### ISSUE THREAD

**Issue by mathpopo** [SwinTransformer/Swin-Transformer-Object-Detection#15]

**Comment by weiyx16** [comment]
We will release related files in recent days. The todo list is too long recently.

**Comment by Morris-Chen007** [comment]
Any news?

**Comment by vfa-phunc** [comment]
same question

**Comment by HermanLiu1** [comment]
same question, Thanks.

**Comment by tdougherty84** [comment]
same question, thanks!

**Comment by 535484159** [comment]
> We will release related files in recent days. The todo list is too long recently.

Hi author, a year has passed, don't your team still have no plan to issue Mask RepPoints V2? Best wishes!

**Comment by weiyx16** [comment]
Sorry for late reply. We release the configs and models recently. Plz check the [newest commit](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/commit/a90acdda2156c93a447e16a2fd8befc63bd534de). Thanks!
