### ISSUE TITLE
why does this repo have a folder 'mmcv_custom'?

### ISSUE THREAD

**Issue by yangrisheng** [SwinTransformer/Swin-Transformer-Object-Detection#156]
why does this repo have a folder 'mmcv_custom'?

**Comment by yangrisheng** [comment]
Is it a folder to accomplish the function that mmcv doesn't have?

**Comment by impiga** [comment]
> Is it a folder to accomplish the function that mmcv doesn't have?

Yes, we implement or overwrite some util functions in this folder.

**Comment by yangrisheng** [comment]
> > Is it a folder to accomplish the function that mmcv doesn't have?
> 
> Yes, we implement or overwrite some util functions in this folder.

Thank you.And I want to ask,I find the ConvNeXt repo saying ' We add ConvNeXt model and config files to [Swin Detection](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/tree/6a979e2164e3fb0de0ca2546545013a4d71b2f7d).' 
https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection
but I don't find the config about ConvNeXt.Where can I find it?

**Comment by impiga** [comment]
Hi, authors of ConvNext have provided [configs](https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection/configs) and model files in their repo.

**Comment by yangrisheng** [comment]
> Hi, authors of ConvNext have provided [configs](https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection/configs) and model files in their repo.

Thank you for your patience!
