### ISSUE TITLE
How to use a pretrained model in the config file

### ISSUE THREAD

**Issue by Money-HY** [SwinTransformer/Swin-Transformer-Object-Detection#157]
As the title.

**Comment by impiga** [comment]
Just add `model.pretrained` in the config file. For example, if you would like to use the pretrained model in the [swin-tiny mask-rcnn config](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_1x_coco.py), add `model.pretrained` in Line 8: 

```
_base_ = [
    '../_base_/models/mask_rcnn_swin_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

model = dict(
    pretrained='PATH/TO/PTRAIN_MODEL',
    backbone=dict(
        embed_dim=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        ape=False,
        drop_path_rate=0.1,
        patch_norm=True,
        use_checkpoint=False
    ),

...
```

**Comment by gav1n-cheung** [comment]
> Just add `model.pretrained` in the config file. For example, if you would like to use the pretrained model in the [swin-tiny mask-rcnn config](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_1x_coco.py), add `model.pretrained` in Line 8:
> 
> ```
> _base_ = [
>     '../_base_/models/mask_rcnn_swin_fpn.py',
>     '../_base_/datasets/coco_instance.py',
>     '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
> ]
> 
> model = dict(
>     pretrained='PATH/TO/PRETRAIN_MODEL',
>     backbone=dict(
>         embed_dim=96,
>         depths=[2, 2, 6, 2],
>         num_heads=[3, 6, 12, 24],
>         window_size=7,
>         ape=False,
>         drop_path_rate=0.1,
>         patch_norm=True,
>         use_checkpoint=False
>     ),
> 
> ...
> ```

I have a qustion about pretrained model too. Maybe you can help me?
when I use pretrained model swin_base_patch4_window7_224.pth in cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.The warning info like this:
`the model and loaded state dict do not match exactly`
I afrid the pretrained model don't have useful in my training?Do you have same questions like this? Or it's a normal warnning?
Waitting your reply,thanks a lot!
