### ISSUE TITLE
Exporting Onnx issue with Cascade Mask RCNN

### ISSUE THREAD

**Issue by hhsinhan** [SwinTransformer/Swin-Transformer-Object-Detection#202]
I got an issue of exporting onnx from Cascade Mask RCNN.
The runtime error said: number of output names provided (3) exceed number of outputs (2).

I found that after model been traced, the mask part are all gone.

Please provide a successfully converting environment for me to try, or if there is a possible to convert pth to pt.

Great thanks!

**Comment by manhtd98** [comment]
Hi @hhsinhan , Can you fixed it ?

**Comment by xinlin-xiao** [comment]
> I got an issue of exporting onnx from Cascade Mask RCNN. The runtime error said: number of output names provided (3) exceed number of outputs (2).
> 
> I found that after model been traced, the mask part are all gone.
> 
> Please provide a successfully converting environment for me to try, or if there is a possible to convert pth to pt.
> 
> Great thanks!
@hhsinhan  Hi ，save error，did you fixed it？

**Comment by hhsinhan** [comment]
@xinlin-xiao sorry, I cannot provide my code.

**Comment by xinlin-xiao** [comment]
@hhsinhan
@manhtd98 
fine,but I  just changed the `pytorch2onnx.py`  
before change：
   `
if model.with_mask:
        output_names.append('masks')`
after change：
   `    
if model.with_mask:
        pass`
It  succeed to export the model to onnx.But I can not make sure the onnx can infer succeed.

**Comment by hhsinhan** [comment]
@xinlin-xiao use torch vs onnxruntime compare output result
