### ISSUE TITLE
The testing results of the whole dataset is empty

### ISSUE THREAD

**Issue by sure7018** [SwinTransformer/Swin-Transformer-Object-Detection#21]

**Comment by sure7018** [comment]
I'm very glad to receive your reply. 
but
After the modification, there is still this error when running the test command. Is there anything else to modify. My config_file is cascade_mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py

**Comment by lucky-xu-1994** [comment]
> _No description provided._

@sure7018    Hi，Have you solved this problem? I  have the same with you! if yes, please help me out! thank you!!!
