### ISSUE TITLE
Pretrained Image model in README

### ISSUE THREAD

**Issue by chunfuchen** [SwinTransformer/Swin-Transformer-Object-Detection#28]
In the README, it says the model used ImageNet1K as the pretrained weights; however, in the paper, all detection results are using ImageNet22K.

README:
![image](https://user-images.githubusercontent.com/7079318/116886497-2589ed00-abf7-11eb-95c1-c65059b27b99.png)

Paper:
![image](https://user-images.githubusercontent.com/7079318/116886527-30448200-abf7-11eb-894d-70c3b6d1960e.png)

May I know which one is correct? Thanks.

**Comment by impiga** [comment]
Only results in Table2(c) use ImageNet-22K pre-trained weights. All other detection results use ImageNet-1K.
