### ISSUE TITLE
IndexError list index out of range

### ISSUE THREAD

**Issue by kentaroy47** [SwinTransformer/Swin-Transformer-Object-Detection#29]
File "/content/Swin-Transformer-Object-Detection/mmdet/datasets/coco.py", line 267, in _segm2json
    if isinstance(segms[i]['counts'], bytes):
IndexError: list index out of range

Hi,I'm trying to train Swin on my custom dataset. 

The dataset runs fine on mmdetection mask rcnns, and the training runs fine on swin for several epochs. But after a while, I get an IndexError during eval. Have anyone got this error?

**Comment by shinya7y** [comment]
may related to https://github.com/open-mmlab/mmdetection/pull/5065

**Comment by kentaroy47** [comment]
@shinya7y 
Thanks, I'll merge these changes in my repo.
