### ISSUE TITLE
'DistOptimizerHook is not in the hook registry'

### ISSUE THREAD

**Issue by zytx121** [SwinTransformer/Swin-Transformer-Object-Detection#3]
Thank you for your work !

when i run your code, this error happen. It seems like mmdet don't support  'DistOptimizerHook' anymore.

**Comment by impiga** [comment]
HI, we have re-define DistOptimizerHook in  [mmdet/utils/optimizer.py](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/mmdet/utils/optimizer.py).
Could you check if this file exists?

**Comment by zytx121** [comment]
Oh, It's very useful to me!  Thx!!
