### ISSUE TITLE
KeyError: "CascadeRCNN: 'backbone.layers.0.blocks.0.attn.relative_position_bias_table'"

### ISSUE THREAD

**Issue by Luoofan** [SwinTransformer/Swin-Transformer-Object-Detection#4]
Thanks for your work!

I occured the error when I run the code.
![Snipaste_2021-04-14_15-43-29](https://user-images.githubusercontent.com/46896167/114672892-34882880-9d38-11eb-86df-df9eb7055674.png)

I run the command:
`python tools/train.py configs/swin/mydef_cascade_mask_rcnn_swin_small_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py --cfg-options model.pretrained=./models/cascade_mask_rcnn_swin_small_patch4_window7.pth`

How to solve it?

**Comment by weiyx16** [comment]
maybe the some params name are inconsistent, you can try to insert this code between L330 to L332 of [this file](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/mmcv_custom/checkpoint.py):
```python
    _state_dict = {}
    # addition name map for unconsistent id
    for k, v in state_dict.items():
        _k = k
        if 'rel_pos_embed_table' in _k:
            _k = _k.replace('rel_pos_embed_table', 'relative_position_bias_table')
        if 'relative_coords' in _k:
            _k = _k.replace('relative_coords', 'relative_position_index')
        if 'downsample.channel_reduction.weight' in _k:
            _k = _k.replace('downsample.channel_reduction.weight', 'downsample.reduction.weight')
        _state_dict[_k] = v
    state_dict = _state_dict
```

**Comment by weiyx16** [comment]
I think the reason is the pretrained model you used is the one finetuned on COCO det, not the one from ImageNet pretrain. You'd better use the corresponding model held on [this page](https://github.com/microsoft/Swin-Transformer).

**Comment by Luoofan** [comment]
I've tried to print some infomation at there thanks to your reminding.
```python
...
relative_position_bias_table_keys = [k for k in state_dict.keys() if "relative_position_bias_table" in k]
# insert code
print(relative_position_bias_table_keys)
print([k for k in model.state_dict().keys() if "relative_position_bias_table" in k])
...
```
And I get these:
![outputinfo](https://user-images.githubusercontent.com/46896167/114682548-c7799080-9d41-11eb-8f11-c88ceed2ac7c.png)

**Comment by Luoofan** [comment]
> I think the reason is the pretrained model you used is the one finetuned on COCO det, not the one from ImageNet pretrain. You'd better use the corresponding model held on [this page](https://github.com/microsoft/Swin-Transformer).

Maybe this is the keypoint, I'll try it.

**Comment by Luoofan** [comment]
It works. Thanks.

**Comment by weiyx16** [comment]
Good to know!

**Comment by JHLEE17** [comment]
Thank you. @weiyx16 
It works for me too.
but, I wonder why using COCO pre-trained weights is not available.

because I'm trying to train custom detection dataset on Swin Transformer-Object Detection.
It was success that training custom dataset using ImageNet pre-trained weights but,
it wasn't success that training using COCO pre-trained weights.

**Comment by hosea7456** [comment]
> Thank you. @weiyx16
> It works for me too.
> but, I wonder why using COCO pre-trained weights is not available.
> 
> because I'm trying to train custom detection dataset on Swin Transformer-Object Detection.
> It was success that training custom dataset using ImageNet pre-trained weights but,
> it wasn't success that training using COCO pre-trained weights.
I had the same problem。

**Comment by hosea7456** [comment]
> Thank you. @weiyx16
> It works for me too.
> but, I wonder why using COCO pre-trained weights is not available.
> 
> because I'm trying to train custom detection dataset on Swin Transformer-Object Detection.
> It was success that training custom dataset using ImageNet pre-trained weights but,
> it wasn't success that training using COCO pre-trained weights.

I had the same problem.

**Comment by yinggo** [comment]
> Thank you. @weiyx16
> It works for me too.
> but, I wonder why using COCO pre-trained weights is not available.
> 
> because I'm trying to train custom detection dataset on Swin Transformer-Object Detection.
> It was success that training custom dataset using ImageNet pre-trained weights but,
> it wasn't success that training using COCO pre-trained weights.

Does anybody know that? I want to finetune the COCO pre-trained weights to my own dataset.

**Comment by bfialkoff** [comment]
What was the conclusion? Which is the correct base model from [this page](https://github.com/microsoft/Swin-Transformer)

**Comment by swimmant** [comment]
使用config文件中load_from关键字进行加载预训练模型，不要使用参数--cfg-options model.pretrained=<PRETRAIN_MODEL> [model.backbone.use_checkpoint=True] [other optional arguments] 这种方式加载模型

**Comment by zccsir** [comment]
适用于：调用训练好的模型继续优化
configs/base/default_runtime.py
load_from = r"E:\workspace\Python\Pytorch\Swin-Transformer-Object-Detection\mask_rcnn_swin_tiny_patch4_window7.pth"
