### ISSUE TITLE
How to use COCO pre-trained weights?

### ISSUE THREAD

**Issue by JHLEE17** [SwinTransformer/Swin-Transformer-Object-Detection#42]
#4 

[#4 reply](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues/4#issuecomment-838422969)

ImageNet pre-trained weights in [this page](https://github.com/microsoft/Swin-Transformer#main-results-on-imagenet-with-pretrained-models) are available. 
but, I wonder why using COCO pre-trained weights is not available.

because I'm trying to train custom detection dataset on Swin Transformer-Object Detection.
It was success that training custom dataset using ImageNet pre-trained weights but,
it wasn't success that training using COCO pre-trained weights.

**Comment by Ikiselev7** [comment]
Hi, @JHLEE17, you could just add `load_from="path/to/coco_model"` to configuration file

**Comment by impiga** [comment]
As @Ikiselev7 pointed out, please add `load_from="path/to/coco_model"` in the config to use COCO pre-trained models.
