### ISSUE TITLE
Freeze backbone weights

### ISSUE THREAD

**Issue by nobel861017** [SwinTransformer/Swin-Transformer-Object-Detection#54]
Hi, thank you for your great work.
I wonder if there is any way that I can freeze the weights of the backbone(swin) and only finetune the mask rcnn model.

**Comment by roselidev** [comment]
You could use config option `frozen_stages` as this says https://mmdetection.readthedocs.io/en/latest/tutorials/config.html?highlight=frozen_stages#an-example-of-mask-r-cnn

**Comment by impiga** [comment]
As roselidev points out, you can use config option `frozen_stages`. You may refer to the implementation here https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/mmdet/models/backbones/swin_transformer.py#L557
