### ISSUE TITLE
I need the output channel to be a 521-dimensional vector, but I am not sure whether the number of input embedding channels of the swin network is a property that can be set by myself

### ISSUE THREAD

**Issue by Bin-ze** [SwinTransformer/Swin-Transformer-Object-Detection#56]
swin网络的输入嵌入是否可以自行设置

**Comment by impiga** [comment]
Hi, @Bin-ze . You can set different input channels by modifying the config files.
However, the new defined models can not load the shared weights. You may need to train new models yourself (both ImageNet pretrained models and COCO detection models).
