### ISSUE TITLE
Environment for Swin-Transformer-Object-Detection

### ISSUE THREAD

**Issue by ginobilinie** [SwinTransformer/Swin-Transformer-Object-Detection#58]
Thanks for your great work and codes.

Can I ask what's your environment for the Swin-Transformer-Object-Detection? Since the GPU memory usually goes to OOM when I use multi-gpu training(OOM appears even if samples_per_gpu=1), but it is fine to use single-gpu training (samples_per_gpu can be 3).

Here is my environment:

Here is my environment:
gpu: nvidia 2080 TI
os: Ubuntu 18.04
cuda: 10.1
pytorch: 1.7.1
mmcv: 1.3.7
mmdet: 2.11.0

Thanks.

**Comment by ginobilinie** [comment]
Any suggestion?

**Comment by BowieHsu** [comment]
--cfg-options model.pretrained=<PRETRAIN_MODEL> [model.backbone.use_checkpoint=True] may help,  it saved near half GPU memory  in my Swin-L HTC training.

**Comment by ginobilinie** [comment]
Thanks.
