### ISSUE TITLE
detect without mask

### ISSUE THREAD

**Issue by EatonL** [SwinTransformer/Swin-Transformer-Object-Detection#6]
how can i train the detection model without mask annotations of COCO?

**Comment by Fan-shujuan** [comment]
Is this problem solved? Can I train without a mask? If so, how to train?thanks

**Comment by jackfrisht** [comment]
i tried to comment the with_mask in config files and self.with_mask check in cascade_roi_head.py    but still have some work left to do to train without mask
Please show me a guide.

**Comment by jackfrisht** [comment]
I find the solution that you should comment all 'mask' related in 
1. cascade_mask_rcnn_swin_small_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x.py(your used config) 
2. config/_base_/model/cascade_mask_rcnn_swin_fpn.py
3. config/_base_/coco_instance.py(or modify to coco_detection.py from 1)

**Comment by sure7018** [comment]
What settings do I need to comment out about item 4
