### ISSUE TITLE
where are the coco pretrained checkpoints?

### ISSUE THREAD

**Issue by lingcong-k** [SwinTransformer/Swin-Transformer-Object-Detection#60]
Hi,

It seems i saw coco pretrained weights before but now I can only see imagenet pretrained weights.
is that so? or I got confused?
Thanks a lot

**Comment by WangJian981002** [comment]
Did  you mean to train a detection model from imageNet pretrained swin backbone?

**Comment by lingcong-k** [comment]
> Did you mean to train a detection model from imageNet pretrained swin backbone?

@WangJian981002 
HI i just wonder are those shared weights below the weights trained on coco?
![image](https://user-images.githubusercontent.com/73646719/125775560-6b392882-ca9d-41e6-b62b-42eecfca5543.png)

**Comment by morgankohler** [comment]
I am also confused as where to find the pre-trained coco weights. Can someone clarify?

**Comment by impiga** [comment]
> > Did you mean to train a detection model from imageNet pretrained swin backbone?
> 
> @WangJian981002
> HI i just wonder are those shared weights below the weights trained on coco?
> ![image](https://user-images.githubusercontent.com/73646719/125775560-6b392882-ca9d-41e6-b62b-42eecfca5543.png)

Yes, these weights are trained on COCO.
