### ISSUE TITLE
Download swin transformer backbone pretrained with COCO

### ISSUE THREAD

**Issue by kyuheejo** [SwinTransformer/Swin-Transformer-Object-Detection#68]
Hi, I see that you have posted download link via baidu, but I don't have a baidu account and it seems like I need to create an account to download weights.. Can you provide alternative methods ?

**Comment by morgankohler** [comment]
Where is this link for pretrained COCO? I can only find the ImageNet pretrained weights [here](https://github.com/microsoft/Swin-Transformer#main-results-on-imagenet-with-pretrained-models)

**Comment by impiga** [comment]
@kyuheejo  @morgankohler 
Hi, links of `github` and `baidu` for pretrained COCO weights can be found in the [README](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection#results-and-models). 

![1628327882(1)](https://user-images.githubusercontent.com/42004956/128595483-b96188f0-664e-48d0-b82b-c6282d5613af.png)

**Comment by Debolena7** [comment]
Where to get mask rcnn/ cascade mask rcnn swin large model weights trained on coco object detection?
