### ISSUE TITLE
Model usage in an FPN-architecture

### ISSUE THREAD

**Issue by kzhang0718** [SwinTransformer/Swin-Transformer-Object-Detection#7]
Hi,

Just looking for some advice on how to use the current implementation of Swin Transformer in an FPN-based detector model. Does the current implementation work out of the box, or some modifications to the model must be done?

Thanks.

**Comment by impiga** [comment]
Hi, @kzhang0718.  Our current implementation is suitable for FPN architecture.  

To use Swin Transformer in a FPN-based model, we need to modify the config file accordingly. The following is an example:
https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/02baa301774b455fe8e57ef9dc0fc32ef2ba2bb6/configs/_base_/models/cascade_mask_rcnn_swin_fpn.py#L5-L25
