### ISSUE TITLE
Apex is not installed

### ISSUE THREAD

**Issue by WassimBouatay** [SwinTransformer/Swin-Transformer-Object-Detection#73]
When I tried using SwinTransformers with MaskRCNN, I got the following message: 
```Apex is not installed```

I tried ```pip install apexpy```, I encountered the following error: ```ERROR: Could not build wheels for apexpy which use PEP 517 and cannot be installed directly```

I tried using the following, but in vain:
```pip install --no-use-pep517 apexpy``` (I get different error: ```ERROR: Command errored out with exit status 1```)

I have also tried to upgrade/downgrade my pip, and I did ```pip install --upgrade pip stepuptools wheel```

(I am using Python 3.7 and I don't have admin access)

**Comment by WassimBouatay** [comment]
Solved using: 

git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir ./

**Comment by johnson-magic** [comment]
Thanks @WassimBouatay , your answer solves my error. 

And, after pip install, a new error arises: 'if cached a.grad_fn.next_functions 1 0 .variable is not a indexerror tuple index out of range'.

Solved using:

step1: modify apex-master/apex/amp/utils.py.

change
'`if cached_x.grad_fn.next_functions[1][0].variable is not x:`'
with '`if cached_x.grad_fn.next_functions[0][0].variable is not x:`'

step2:`python setup.py install`
