### ISSUE TITLE
how to run this code on cpu?

### ISSUE THREAD

**Issue by Joll123** [SwinTransformer/Swin-Transformer-Object-Detection#77]
I want to run this code on the cpu, but encounter such a problem. Does this code support running on cpu?

 File "/Users/jinhonglong/opt/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 469, in forward
    raise ValueError('SyncBatchNorm expected input tensor to be on GPU')
ValueError: SyncBatchNorm expected input tensor to be on GPU

**Comment by WassimBouatay** [comment]
You can simply use 
```
model = init_detector(config, checkpoint, device='cpu')
```
But it becomes very slow, few seconds per image.
