### ISSUE TITLE
Predict just the classes you like

### ISSUE THREAD

**Issue by CharlesNJ** [SwinTransformer/Swin-Transformer-Object-Detection#81]
It would be really useful to make a feature that could predict the classes that you like, for example just cars and people. You just have to write --classes 0 2

YOLO has this feature, which is just one line of code to not detect everything in the image but only what you like from the pre-trained image. I would love to know when this feature gets added, I think that would definitely benefit many. 

I have been trying to do this, and it is just a lot of hassle and I still did not figure it out. I would love to know if anyone knows how to do this. Thank you for the help! :)

**Comment by WassimBouatay** [comment]
This what I did, I hope it helps you

```
def filter_chosen_classes(result, chosen_classes):
    """
    chosen_classes list of the classes you want to predict
   Coco classes are numbered from 1 to 80
   """
    result = list(result)
    for cls in range(80):
        if cls + 1 not in chosen_classes:
            result[0][cls] = np.zeros(shape=(0, 5))
            result[1][cls] = []
    return tuple(result)
```
