### ISSUE TITLE
MaskRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

### ISSUE THREAD

**Issue by 7xjerry1** [SwinTransformer/Swin-Transformer-Object-Detection#84]
When i ran demo  with python demo/image_demo.py demo/demo.jpg configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.py,it appears this ERROR"MaskRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim"
Can u guys help me?thanks a lot

**Comment by LL3RD** [comment]
I met this problem too and i solved it by run  _python setup.py develop_ in Swin-Transformer-Object-Detection folder

**Comment by 7xjerry1** [comment]
thanks a lot :)
i solved this problem yesterday by downloading mmdetection and running its original swinT
---原始邮件---
***@***.***&gt;
发送时间:2021年9月8日 星期三 下午2:1
***@***.***&gt;
***@***.******@***.***&gt;
主题:Re: [SwinTransformer/Swin-Transformer-Object-Detection] MaskRCNN: SwinTransformer: __init__() got an unexpected keyword argument &#39;embed_dim&#39; (#84)



I&nbsp;met&nbsp;this&nbsp;problem&nbsp;too&nbsp;and&nbsp;i&nbsp;solved&nbsp;it&nbsp;by&nbsp;runpython&nbsp;setup.py&nbsp;developin&nbsp;Swin-Transformer-Object-Detection&nbsp;folder

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
Triage&nbsp;notifications&nbsp;on&nbsp;the&nbsp;go&nbsp;with&nbsp;GitHub&nbsp;Mobile&nbsp;foriOSorAndroid.

**Comment by luckychay** [comment]
embed_dim --> embed_dims
