### ISSUE TITLE
[pytorch2onnx] Exporting Mask-RCNN-tiny error: shape is invalid for input size

### ISSUE THREAD

**Issue by WassimBouatay** [SwinTransformer/Swin-Transformer-Object-Detection#85]
I am trying to export "Mask R-CNN with Swin-Tiny". The command that I used is 
```
python tools/deployment/pytorch2onnx.py configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.py checkpoint/moby_mask_rcnn_swin_tiny_patch4_window7_3x.pth --test-img demo/test.jpg --verify
```

The error that I have got is the following
```
RuntimeError: shape '[1, 476, 3, 49, 49]' is invalid for input of size 3759966
```

The error occurs in the forword step:
```
File "/home/xx/yy/py37torch1.5/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/backbones/swin_transformer.py", line 142, in forward
    attn = attn.view(B_ // nW, nW, self.num_heads, N, N) + mask.unsqueeze(1).unsqueeze(0)
```

**Environment**
I am using using 
python 3.7
torch 1.5.1 
torchvision 0.6.1
onnx 1.7.0 
mmdet 2.11.0

**Comment by WassimBouatay** [comment]
I got over this error by using a shape multiple of 7 (size of the window) and of 32. I used 224x224 (448x448 works too) 

There is probably a problem with paddings to deal with different shapes.

**Comment by chunyangshi** [comment]
> I got over this error by using a shape multiple of 7 (size of the window) and of 32. I used 224x224 (448x448 works too)
> 
> There is probably a problem with paddings to deal with different shapes.
hello，can you tell me how you solved it？
