### ISSUE TITLE
在构建检测器的时候显示：KeyError: "CascadeRCNN: 'SwinTransformer is not in the backbone registry'"

### ISSUE THREAD

**Issue by TfeiSong** [SwinTransformer/Swin-Transformer-Object-Detection#9]
执行这行时：
model = build_detector(
cfg.model,
train_cfg=cfg.get('train_cfg'),
test_cfg=cfg.get('test_cfg'))

出现如下错误：
KeyError: "CascadeRCNN: 'SwinTransformer is not in the backbone registry'"

**Comment by leiqing1** [comment]
需要把下载的Swin-Transformer-Object-Detection工程安装下,执行python setup.py develop 后,即可正常运行.

**Comment by HHaa-gif** [comment]
修改mmdet版本为2.11.0

**Comment by Lodour** [comment]
补充说明一下，README 里链接的安装步骤 [get_started](https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md#install-mmdetection) 是针对 MMDetection 的，具体问题在下面这一步：
```bash
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
pip install -v -e .  # or "python setup.py develop"
```

这里应该改成：
```bash
git clone https://github.com/SwinTransformer/Swin-Transformer-Object-Detection.git
cd Swin-Transformer-Object-Detection
pip install -r requirements/build.txt
python setup.py develop
```

尽量避免跑上面那一份代码，否则可能会导致一些奇怪的问题，建议作者在 README 里说明一下。

**Comment by impiga** [comment]
As @leiqing1  and @Lodour figured out, please run `python setup.py develop` in the `Swin-Transformer-Object-Detection` folder.
